---
# FEATURE_NAME: build_and_dispatch_docker_images
# FEATURE_VERSION: build_and_dispatch_docker_images-v5.1.3
# FEATURE_URL: https://github.com/prefapp/features/tree/build_and_dispatch_docker_images-v5.1.3/packages/build_and_dispatch_docker_images

name: Trigger dispatches on pre-releases
run-name: Trigger dispatches on new pre-releases built at "${{ github.event.workflow_run.head_sha }}"

on:
  workflow_run:
    workflows: ["Build Docker pre-releases"]
    types:
      - completed

permissions:
  actions: write
  contents: read

jobs:
  on-success:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'workflow_dispatch' }}
    steps:
      - name: Dispatch image changes to state repos
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'The triggering workflow passed'
          gh workflow run make_dispatches.yaml -R ${{ github.repository }} \
          -f image_type=snapshots \
          -f flavors='*' \
          -f filter_by_env="pre" \
          -f workflow_run_id="${{ github.event.workflow_run.id }}"
